#!/bin/bash

# fgdeploy
# Copyright 2020 Joao Eriberto Mota Filho
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Version 0.4 - 03 Nov 2020
#
# * Updated the manpage.
#
# Version 0.3 - 01 Nov 2020
#
# * Added 'exit 0' to avoid errors with autopkgtest command.
#
# Version 0.2 - 31 Oct 2020
#
# * Added original-files as option.
#
# Version 0.1 - 16 Sep 2020
#
# * Initial release.

function help() {
cat << EOF

    forensics-samples deploy tool for Debian
    version 0.4

    Usage: fsdeploy <file.xz>
           or
           fsdeploy original-files

    PS: your system must provide a \$AUTOPKGTEST_TMP variable.
EOF
exit 1
}

# No file?
[ "$1" ] || help

# No $AUTOPKGTEST_TMP?
[ "$AUTOPKGTEST_TMP" ] || { echo ERROR: \$AUTOPKGTEST_TMP not found.; help; }

# File exist?
TEST=$(ls /usr/share/forensics-samples/$1)
[ "$TEST" ] || { echo ERROR: File /usr/share/forensics-samples/$1 not found.; help; }

# unxz exist?
TEST=$(unxz -h | grep decompress)
[ "$TEST" ] || { echo ERROR: Command unxz not found.; help; }

# Copy and decompress file
cp -a /usr/share/forensics-samples/$1 $AUTOPKGTEST_TMP
cd $AUTOPKGTEST_TMP
[ "$1" != "original-files" ] && unxz $1

exit 0
